server:
  port: 7100
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.83:8848
    gateway:
      #      enabled: true
      #      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
      #        - id: shop-product # 当前路由的标识, 要求唯一
      #          uri:  lb://shop-product # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
      ##          uri: http://localhost:7001 # 请求要转发到的地址
      #          order: 1 # 路由的优先级,数字越小级别越高
      #          predicates: # 断言(就是路由转发要满足的条件)
      #            - Path=/shop-product/** # 当请求路径满足Path指定的规则时,才进行路由转发
      #          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
      #            - StripPrefix=1 # 转发之前去掉1层路径
#            discovery:
#              locator:
#                enabled: true # 注册中心探测器-访问方式服务名加路径

      #      routes:
      #        # 路由id
      #        - id: shop-product
      #          # 匹配后提供服务路由地址
      #          uri: lb://shop-product
      #          # 断言
      #          predicates:
      #            # curl http://localhost:9527/payment/get/1
      #            - Path=/shop-product/**
      #
      #            # 自定义Pid断言工厂
      #            # Pid：自动找到 "Pid" + "RoutePredicateFactory" 断言工厂
      #            # 0,100: 断言工厂参数
      #            # 限制产品id[1, 100)的人能访问
      #            - Pid=1,100
      #          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
      #            - StripPrefix=1 # 转发之前去掉1层路径

      discovery:
        locator:
          enabled: true # 注册中心探测器-访问方式服务名加路径
      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: shop-product # 当前路由的标识, 要求唯一
          uri: lb://shop-product # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          #          uri: http://localhost:7001 # 请求要转发到的地址
          order: 1 # 路由的优先级,数字越小级别越高
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/shop-product/** # 当请求路径满足Path指定的规则时,才进行路由转发
            - Pid=1,100
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 # 转发之前去掉1层路径
            - SetStatus=2000 # 修改返回状态
            - Log=true,false
  zipkin:
    base-url: http://192.168.10.83:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比