globalConfig:
  tenants1: &tenants1 TenantCode=6666,1011,1012,1013
  tenants2: &tenants2 TenantCode=8054,2156,7116,1028,7857,3979,8211,5670,5695,7832,4212,5359,1026,0961,3725,3252,7012,3658,3125,9635,2589,7526,4562,1019,8526
  myReadBodyArgs: &myReadBodyArgs
      inClass: '#{T(String)}'
      predicate: '#{@bodyPredicate}'
server:
  port: 7101
spring:
  application:
    name: gateway-predicates
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

      routes:
        - id: tenants1 # 当前路由的标识, 要求唯一
          uri: &uri1 http://192.168.2.55:8080
          order: 3 # 路由的优先级,数字越小级别越高
          predicates: # 断言(就是路由转发要满足的条件)
            - *tenants1


        - id: tenants2
          uri: &uri2 http://192.168.2.55:8083
          order: 3
          predicates:
            - *tenants2

        - id: tenantsBody1
          uri: *uri1
          order: 2
          predicates:
            - Path=/employee/login
            - name: MyReadBody #使用ReadBodyPredicateFactory断言，将body读入缓存
              args: *myReadBodyArgs
            - *tenants1

        - id: tenantsBody2
          uri: *uri2
          order: 2
          predicates:
            - Path=/employee/login
            - name: MyReadBody
              args: *myReadBodyArgs
            - *tenants2


        - id: tenants0000 #未命中默认转这
          uri: *uri1
          #          uri: http://192.168.2.55:8080
          order: 10
          predicates:
            - Path=/**


logging:
  file:
    path: /var/logs/gateway
  level:
    root: info
    org.kenshin.gatewaypredicates: debug
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.loadbalancer: trace
    org.springframework.web.reactive: trace

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: saas-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  redisExpiration: 14400
  redisRenewal: 2400
  tokenHead: 'Bearer '  #JWT负载中拿到开头