#服务名称
spring:

  application:
    name: commodityCenter


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.83:3306/db_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root


server:
  port: 6002




mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    map-underscore-to-camel-case: false
    mapUnderscoreToCamelCase: true # 下划线转驼峰
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





