spring:
  application:
    name: shop-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.83:8848

  zipkin:
    base-url: http://192.168.10.83:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比

server:
  port: 7001